### ISSUE TITLE
git module missing after installation

### ISSUE THREAD

**Issue by alexfoias** [sct-pipeline/spine-generic#21] opened 2019-03-01 16:58 UTC
Reported by users. 

Here are the steps to reproduce: 
```
tsf-452-wpa-6-235:spine_generic nawal$ pip install -r requirements.txt
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already satisfied: gitpython in /Library/Python/2.7/site-packages (from -r requirements.txt (line 1)) (2.1.11)
Requirement already satisfied: logging in /Library/Python/2.7/site-packages (from -r requirements.txt (line 2)) (0.4.9.6)
Requirement already satisfied: gitdb2>=2.0.0 in /Library/Python/2.7/site-packages (from gitpython->-r requirements.txt (line 1)) (2.0.5)
Requirement already satisfied: smmap2>=2.0.0 in /Library/Python/2.7/site-packages (from gitdb2>=2.0.0->gitpython->-r requirements.txt (line 1)) (2.0.5)
```

But I still have an error when converting the files:

```
tsf-452-wpa-6-235:spine_generic nawal$ python convert_dcm2bids.py -d /Users/nawal/Desktop/YF -s sub-01 -o /Users/nawal/Desktop/gva_spinegeneric/
Traceback (most recent call last):
  File "convert_dcm2bids.py", line 13, in <module>
    import os, glob, argparse, shutil, tempfile, logging, subprocess, git, platform
ImportError: No module named git
```

**Comment by alexfoias** [comment] 2019-03-01 16:59
possible solution suggested by @jcohenadad : use conda env during install, or by force py3k support only

**Comment by NKin01** [comment] 2019-03-01 17:45
Unfortunately, I can't make it work with Python3 either

```
tsf-452-wpa-6-235:spine_generic nawal$ pip3 install -r requirements.txt
Collecting gitpython (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/fe/e5/fafe827507644c32d6dc553a1c435cdf882e0c28918a5bab29f7fbebfb70/GitPython-2.1.11-py2.py3-none-any.whl
Collecting logging (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/93/4b/979db9e44be09f71e85c9c8cfc42f258adfb7d93ce01deed2788b2948919/logging-0.4.9.6.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/logging.egg-info
    writing pip-egg-info/logging.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/logging.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/logging.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/logging.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/d6/7hc1qnqn1g324cq7w6467d1r0000gp/T/pip-install-7tg2tr2a/logging/setup.py", line 13, in <module>
        packages = ["logging"],
      File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 296, in run
        self.find_sources()
      File "/usr/local/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 303, in find_sources
        mm.run()
      File "/usr/local/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 534, in run
        self.add_defaults()
      File "/usr/local/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 570, in add_defaults
        sdist.add_defaults(self)
      File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/sdist.py", line 226, in add_defaults
        self._add_defaults_python()
      File "/usr/local/lib/python3.7/site-packages/setuptools/command/sdist.py", line 127, in _add_defaults_python
        build_py = self.get_finalized_command('build_py')
      File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 298, in get_finalized_command
        cmd_obj = self.distribution.get_command_obj(command, create)
      File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 857, in get_command_obj
        klass = self.get_command_class(command)
      File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 845, in get_command_class
        self.cmdclass[command] = cmdclass = ep.load()
      File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
        return self.resolve()
      File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/usr/local/lib/python3.7/site-packages/setuptools/command/build_py.py", line 15, in <module>
        from setuptools.lib2to3_ex import Mixin2to3
      File "/usr/local/lib/python3.7/site-packages/setuptools/lib2to3_ex.py", line 12, in <module>
        from lib2to3.refactor import RefactoringTool, get_fixers_from_package
      File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib2to3/refactor.py", line 18, in <module>
        import logging
      File "/private/var/folders/d6/7hc1qnqn1g324cq7w6467d1r0000gp/T/pip-install-7tg2tr2a/logging/logging/__init__.py", line 618
        raise NotImplementedError, 'emit must be implemented '\
                                 ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/d6/7hc1qnqn1g324cq7w6467d1r0000gp/T/pip-install-7tg2tr2a/logging/
```

**Comment by jcohenadad** [comment] 2019-03-01 17:54
Related to: https://github.com/neuropoly/bids_neuropoly/issues/8

**Comment by jcohenadad** [comment] 2019-03-01 17:56
@NKin01 maybe it's a permission issue. Could you please try again with your native python, but doing this instead:
```
sudo pip install -r requirements.txt
```

**Comment by jcohenadad** [comment] 2019-03-01 18:04
Actually, the original issue is likely a permission issue, however [this one](https://github.com/sct-pipeline/spine-generic/issues/21#issuecomment-468749735) is likely related to this: https://stackoverflow.com/questions/32386469/logging-module-not-working-with-python3

**Comment by jcohenadad** [comment] 2019-03-01 18:08
Can be fixed by forcing to you py2k pip:
~~~
sudo pip2 install -r requirements.txt
~~~

**Comment by NKin01** [comment] 2019-03-01 18:33
Unfortunately, it seems that the problem is the same using sudo.

```
tsf-452-wpa-6-235:spine_generic nawal$ sudo pip2 install -r requirements.txt
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
The directory '/Users/nawal/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/nawal/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: gitpython in /Library/Python/2.7/site-packages (from -r requirements.txt (line 1)) (2.1.11)
Requirement already satisfied: logging in /Library/Python/2.7/site-packages (from -r requirements.txt (line 2)) (0.4.9.6)
Requirement already satisfied: gitdb2>=2.0.0 in /Library/Python/2.7/site-packages (from gitpython->-r requirements.txt (line 1)) (2.0.5)
Requirement already satisfied: smmap2>=2.0.0 in /Library/Python/2.7/site-packages (from gitdb2>=2.0.0->gitpython->-r requirements.txt (line 1)) (2.0.5)
tsf-452-wpa-6-235:spine_generic nawal$ python convert_dcm2bids.py -d /Users/nawal/Desktop/YF -s sub-01 -o /Users/nawal/Desktop/gva_spinegeneric/
Traceback (most recent call last):
  File "convert_dcm2bids.py", line 13, in <module>
    import os, glob, argparse, shutil, tempfile, logging, subprocess, git, platform
ImportError: No module named git
```

As for the other problem with the logging module, I don't think I can use the same method, as I can't delete /private/var/folders/d6/7hc1qnqn1g324cq7w6467d1r0000gp/T/pip-install-7tg2tr2a/ (actually doesn't exist).

Thanks a lot for the help!

**Comment by jcohenadad** [comment] 2019-03-01 18:49
@NKin01 could you please try under a virtual environment:
```bash
virtualenv venv-dcm2bids
source venv-dcm2bids/bin/activate
git clone https://github.com/sct-pipeline/spine-generic.git
cd spine-generic
pip install -r requirements.txt
```
The, the following should run properly:
~~~
python convert_dcm2bids.py -h
~~~

If it does not, could you please copy/paste the entire output of your terminal
thanks

**Comment by NKin01** [comment] 2019-03-01 19:20
Yes  `python convert_dcm2bids.py -h` works, thanks a lot!

But (of course there is a but, sorry...), I still cannot convert:
```
(venv-dcm2bids) tsf-452-wpa-6-235:spine-generic nawal$ python convert_dcm2bids.py -d /Users/nawal/Desktop/YF/ -s sub-01 -o /Users/nawal/Desktop/gva_spinegeneric/
Traceback (most recent call last):
  File "convert_dcm2bids.py", line 153, in <module>
    convert_dcm2bids(args.path_dicom, args.subject, path_out=args.path_output)
  File "convert_dcm2bids.py", line 74, in convert_dcm2bids
    output_catch = subprocess.Popen(cmd, stdout=subprocess.PIPE).communicate()[0]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by jcohenadad** [comment] 2019-03-01 19:39
@NKin01 what happens when you type:
~~~
dcm2niix 
~~~

If it says `command not found`, then it means that path to `dcm2niix` should be declared and added to your `.bashrc`, i.e. add the following line (in bash):
~~~
PATH=${PATH}:PATH_TO_DCM2NIIX
~~~

**Comment by NKin01** [comment] 2019-03-02 08:43
Thanks a lot, everything is working now!

**Closed** 2019-03-02 20:13 UTC
Labels: bug
